### ISSUE TITLE
Add support for tauri-2.0 rc `tauri-conf.json`

### ISSUE THREAD

**Issue by dionysuzx** [tauri-apps/tauri-action#912] opened 2024-09-16 02:08 UTC
As you can see below, the new `tauri-conf.json` for the tauri 2.0 rc is not supported. As the tauri 2.0 API has stabilized, I think it's fair to integrate it now.

```
Run tauri-apps/tauri-action@v0
running npm [ 'install', '-g', '@tauri-apps/cli' ]

added 2 packages in 3s

1 package is looking for funding
  run `npm fund` for details
running tauri [ 'build', '--target', 'aarch64-apple-darwin' ]
       Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devUrl', 'frontendDist' were unexpected)
       Error `tauri.conf.json` error: Additional properties are not allowed ('app', 'bundle', 'identifier', 'productName' were unexpected)
Error: Command failed with exit code 1: tauri build --target aarch64-apple-darwin
```

**Comment by FabianLars** [comment] 2024-09-16 07:30
Closing as a duplicate of issues like #904 (look there for the solution, but feel free to reach out here if something is still unclear).

**Closed as not planned** 2024-09-16 07:30 UTC
