### ISSUE TITLE
set-output deprecated

### ISSUE THREAD

**Issue by mrjackwills** [tauri-apps/tauri-action#347] opened 2022-12-19 19:45 UTC
Running a basic workflow, [as seen here](https://github.com/mrjackwills/obliqoro/blob/main/.github/workflows/create_workflows.yml), at the end of each successful run, one is met with the following error;

```bash
Warning: The 'set-output' command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
```

**Comment by FabianLars** [comment] 2022-12-19 19:57
Duplicate of #319 - fixed on the dev branch. Thanks for the report.

**Closed as not planned** 2022-12-19 19:57 UTC
