### ISSUE TITLE
Portable windows build

### ISSUE THREAD

**Issue by Diogo-Rego** [tauri-apps/tauri-action#542] opened 2023-08-10 11:48 UTC
I have a project in tauri used to create a program, but I don't know the setup to create a portable version of the program for windows in the github workflow

**Comment by FabianLars** [comment] 2023-08-10 12:56
Duplicate of https://github.com/tauri-apps/tauri-action/issues/302. This is not part of this action right now but in the issue i linked there is a workaround at the bottom that may work for you.

**Closed as not planned by FabianLars** 2023-08-10 12:56 UTC
